version: "3"

services:
 jsoncompare:
  image: jsoncompare
  build:
   context: .
  volumes:
   - ".:/app"
  working_dir: "/app"
  ports:
   - "5001:5001"
  command: "pm2-runtime ecosystem.json --env production --watch"
